### ISSUE TITLE
type watchQueryFetchPolicy Not Implemented

### ISSUE THREAD

**Issue by johnthepink** [kgoggin/reason-react-apollo#15]
We have a workaround for now, but we should get the `type watchQueryFetchPolicy` implemented. ❤️

**Comment by kgoggin** [comment]
Fixed in v1.2.0-alpha.3!

![merry christmas](http://www.i-mockery.com/blabber/pics/billy-idol-xmas.gif)

**Comment by johnthepink** [comment]
![billy-idol-gif-1](https://user-images.githubusercontent.com/816517/80009935-bc29b700-8497-11ea-838d-2fb4d08ce92f.gif)
